{{- $password := (randAlphaNum 20) | b64enc }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-db-connect" (include "app.fullname" . ))) }}
{{- if $secret }}
{{- $password = index $secret.data "password" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-db-connect
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ $password }}
stringData:
  databaseName: {{ include "app.db.name" . }}
  username: {{ include "app.db.connectUserName" . }}
  connection.json: {{ printf "{ \"ConnectionStrings:AppDatabase\": \"Server=%s-mssql;Database=%s;User ID=%s;Password=%s;Command Timeout=3;Connect Timeout=2;Max Pool Size=20 \"}" .Release.Name (include "app.db.name" .) (include "app.db.connectUserName" .) ($password | b64dec) | quote }}