{{- $password := (randAlphaNum 20) | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-db-owner" (include "app.fullname" . )))}}
{{- if $secret }}
{{- $password = index $secret.data "password" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-db-owner
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ $password }}
stringData:
  databaseName: {{ include "app.db.name" . }}
  username: "APP_DB_OWNER"
