# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: msa48/msaotusarchitecthomework
  pullPolicy: IfNotPresent
  tag: "3.0.0"

nameOverride: ""
fullnameOverride: ""

replicaCount: 2

podAnnotations: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

metrics:
  serviceMonitor:
    enabled: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: arch.homework
      paths:
        - path: /otusapp/safonov_mv/(.*)
          pathType: Prefix
        - path: /(.*)
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

tolerations: []

affinity: {}

mssql:
  enabled: true
  acceptEula:
    value: "y"
  edition:
    value: Developer
  collation: SQL_Latin1_General_CP1_CI_AS
  lcid: 1033
  image:
    repository: mcr.microsoft.com/mssql/server
    tag: 2017-latest
  persistence:
    enabled: true
    storageClass: "standard"
    dataAccessMode: ReadWriteOnce
    dataSize: 1Gi
    transactionLogAccessMode: ReadWriteOnce
    transactionLogSize: 1Gi
    backupAccessMode: ReadWriteOnce
    backupSize: 1Gi
    masterAccessMode: ReadWriteOnce
    masterSize: 1Gi  