{
 "title": "safonov_mv",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incoming RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{exported_namespace=\"safonov-mv\", ingress=\"app\"}[2m]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_requests{exported_namespace=\"safonov-mv\", exported_service=\"app\",status=~\"[4-5].*\"}[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"safonov-mv\", exported_service=\"app\"}[2m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"safonov-mv\", exported_service=\"app\"}[2m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"safonov-mv\", exported_service=\"app\"}[2m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"safonov-mv\", exported_service=\"app\"}[2m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Inner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Incoming RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (controller, method) (irate(http_requests_received_total{namespace=\"safonov-mv\", service=\"app\"}[2m]))",
     "legendFormat": "{{method }} / {{ controller }}"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (code) (increase(http_requests_received_total{namespace=\"safonov-mv\",service=\"app\"}[1m]))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{namespace=\"safonov-mv\",service=\"app\"}[2m])) by (le, controller))",
     "legendFormat": "{{controller}}/P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{namespace=\"safonov-mv\", service=\"app\"}[2m])) by (le,controller))",
     "legendFormat": "{{controller}}/P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{namespace=\"safonov-mv\",service=\"app\"}[2m])) by (le,controller))",
     "legendFormat": "{{controller}}/P99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(http_request_duration_seconds_bucket{namespace=\"safonov-mv\",service=\"app\"}[2m])) by (le,controller))",
     "legendFormat": "{{controller}}/max"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"safonov-mv\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"safonov-mv\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Connections",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_connections{namespace=\"safonov-mv\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "DB State",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 29 },
   "targets": [
    {
     "expr": "mssql_database_state{namespace=\"safonov-mv\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_database_filesize{namespace=\"safonov-mv\",database=\"application\"}",
     "legendFormat": "{{logicalname}}"
    }
   ]
  }
 ]
}